# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caab5af8c67dae5c42de64afa1d0c4603e47903a942a031807eee63a0991db0c52ff9eb8414b5fb731dd8c17bd91f8962e72f23adaa4c9f4e121b685b40bbfe5

test:
  secret_key_base: ee5910664b90c8d9e9a9ee2c8bc6769bae50aea5294966ca242600f70b967499beec043e9a3c58380e5a31208deeba3f9fe5d7edead428958f72721ed87d251e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
